@startuml
actor "User" as user
node "Kotlin Restful API" {
    component "Controller" as controller
    component "Service" as service
    component "Repository" as repository
}

database "PostgreSql" as database

user --> controller
controller --> service
service --> repository
repository --> database
@enduml